### ISSUE TITLE
Use of removed feature

### ISSUE THREAD

**Issue by Thoralf-M** [najamelan/async_io_stream#2]
Our CI that runs with nightly failed because of https://github.com/rust-lang/rust/pull/82539
```
error[E0557]: feature has been removed
 --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async_io_stream-0.2.0/src/lib.rs:1:40
  |
1 | #![cfg_attr( nightly, feature(doc_cfg, external_doc) )]
  |                                        ^^^^^^^^^^^^ feature has been removed
  |
  = note: use #[doc = include_str!("filename")] instead, which handles macro invocations

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
error: could not compile `async_io_stream`
```

**Comment by najamelan** [comment]
Yep, this is going to hit all my repos. I will update and release ASAP.

**Comment by najamelan** [comment]
Should be fixed in [0.3.2](https://crates.io/crates/async_io_stream/versions). Feel free to re-open if something is still amiss.
